### ISSUE TITLE
How do you enter the meeting in the same instance of browser in which meet was joined?

### ISSUE THREAD

**Issue by sriramcu** [AmanRaj1608/Google-Meet-Scheduler#12]
Suppose I am sleeping and my friend calls me to inform that the host is taking verbal attendance (through the mic). How do I actually enter the meeting to answer attendance? I don't want to open a new chrome window because the host will get a notification that I joined the meeting just before attendance. I want to enter in the same instance of browser in which your application is running.
Nice program by the way, thanks!

**Comment by AmanRaj1608** [comment]
Hi @sriramcu 

You can set `head = false` in `server.js` on line 16.
Using that there will be a chromium instance on which you can quickly open the mic.

Thanks for the compliment 😀

**Comment by sriramcu** [comment]
> Hi @sriramcu
> 
> You can set `head = false` in `server.js` on line 16.
> Using that there will be a chromium instance on which you can quickly open the mic.
> 
> Thanks for the compliment




Ok thanks for the reply.
How can I add a feature to make an automatic voice/wifi/whatsapp call to my phone and also make a beeping noise on the system (using beep command) in case an error is encountered at any stage? Like a try and except. I am not familiar with Javascript that's why I am asking.

Edit: The following error takes place if internet is disconnected:
`
Error: net::ERR_INTERNET_DISCONNECTED at https://accounts.google.com/signin/v2/identifier?flowName=GlifWebSignIn&flowEntry=ServiceLogin
    at navigate (/home/sriram/Google-Meet-Scheduler/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:113:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async FrameManager.navigateFrame (/home/sriram/Google-Meet-Scheduler/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:88:21)
    at async Frame.goto (/home/sriram/Google-Meet-Scheduler/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:405:16)
    at async Page.goto (/home/sriram/Google-Meet-Scheduler/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:826:16)
    at async GoogleMeet.schedule (/home/sriram/Google-Meet-Scheduler/google-meet.js:29:13)
`
And the program doesn't automatically restart once the internet connection returns. How to automatically  reconnect?
